# ======================================
# 应用服务配置文件 (config/config.yaml)
# =========================================
app:
  name: "Bookstore"
  mode: "debug"

server:
  host: "0.0.0.0"
  port: 8030


# ===============================
# 数据库配置
# ===============================
mysql:
  host: "127.0.0.1"   # 数据库地址
  port: 3306          # 端口号（MySQL 默认为 3306，应为整数）
  user: "root"        # 用户名
  password: "root"        # 密码
  database: "bookstore"   # 数据库名称
  charset: "utf8mb4"     # 字符集


# ===============================
# Redis 缓存配置
# ===============================
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 10           # 可选：连接池大小



# ===============================
# JWT 鉴权配置
# ===============================
jwt:
  secret_key: "mysecretkey"
  expire_seconds: 3600


